apiVersion: v1
kind: Namespace
metadata:
  name: chip
  labels:
    istio-injection: enabled
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: chip
  namespace: chip
spec:
  selector:
    istio: ingressgateway
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "chip.tiagots86.com.br" 
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: chip
  namespace: chip
spec:
  hosts:
  - "chip.chip.svc.cluster.local"
  - "chip.tiagots86.com.br"
  gateways:
  - chip
  http:
  - route:
    - destination:
        host: chip
        port:
          number: 8080 
    retries:
      attempts: 3
      perTryTimeout: 500ms
      retryOn: 5xx
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: chip
  namespace: chip
spec:
  host: chip.chip.svc.cluster.local
  trafficPolicy:
    connectionPool:
      tcp:
        maxConnections: 2
      http:
        http1MaxPendingRequests: 10
        maxRequestsPerConnection: 10
    outlierDetection:
      consecutive5xxErrors: 100
      interval: 300ms
      baseEjectionTime: 60s
      maxEjectionPercent: 50
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: chip
  name: chip
  namespace: chip
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chip
  template:
    metadata:       
      labels:
        app: chip
        name: chip
        version: v1
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: "topology.kubernetes.io/zone"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: chip
            
      - maxSkew: 1
        topologyKey: "node.kubernetes.io/instance-type"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: chip

      - maxSkew: 1
        topologyKey: "karpenter.sh/capacity-type"
        whenUnsatisfiable: ScheduleAnyway
        labelSelector:
          matchLabels:
            app: chip


      containers:
      - name: chip
        image: fidelissauro/chip:v1
        ports:
        - containerPort: 8080
          name: http
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            cpu: 250m
            memory: 512Mi            
        startupProbe:
          failureThreshold: 10
          httpGet:
            path: /readiness
            port: 8080
          periodSeconds: 10
        livenessProbe:
          failureThreshold: 10
          httpGet:
            httpHeaders:
            - name: Custom-Header
              value: Awesome
            path: /liveness
            port: 8080
          periodSeconds: 10
        env:
        - name: CHAOS_MONKEY_ENABLED
          value: "false"  
        - name: CHAOS_MONKEY_MODE
          value: "critical" 
        - name: CHAOS_MONKEY_LATENCY
          value: "true"            
        - name: CHAOS_MONKEY_EXCEPTION
          value: "true"   
        - name: CHAOS_MONKEY_APP_KILLER
          value: "true"   
        - name: CHAOS_MONKEY_MEMORY
          value: "true"                                        
      terminationGracePeriodSeconds: 60
---
apiVersion: v1
kind: Service
metadata:
  name: chip
  namespace: chip 
  labels:
    app.kubernetes.io/name: chip
    app.kubernetes.io/instance: chip 
spec:
  ports:
  - name: web
    port: 8080
    protocol: TCP
  selector:
    app: chip
  type: ClusterIP
---
apiVersion: networking.istio.io/v1
kind: ServiceEntry
metadata:
  name: google.com.br
  namespace: chip
spec:
  hosts:
  - google.com.br
  - www.google.com.br
  - google.com
  location: MESH_EXTERNAL
  ports:
  - number: 443
    name: https
    protocol: TLS
  resolution: DNS
# ---
# apiVersion: keda.sh/v1alpha1
# kind: ScaledObject
# metadata:
#   name: chip-high-cpu
#   namespace: chip
# spec:
#   scaleTargetRef:
#     name: chip
#   minReplicaCount: 3
#   maxReplicaCount: 20
#   pollingInterval: 10
#   cooldownPeriod:  30
#   advanced:
#     horizontalPodAutoscalerConfig:
#       behavior:
#         scaleDown:
#           stabilizationWindowSeconds: 60
#         scaleUp:
#           stabilizationWindowSeconds: 20          
#   triggers:
#   - type: cpu
#     metricType: Utilization # 'Utilization' ou 'AverageValue'
#     metadata:
#       value: "40"
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: chip-scheduled-spike
  namespace: chip
spec:
  scaleTargetRef:
    name: chip
  minReplicaCount: 3
  maxReplicaCount: 20  
  triggers:
  - type: cron
    metadata:
      timezone: America/Sao_Paulo  
      start: 40 10 * * *       
      end: 45 20 * * *         
      desiredReplicas: "20"
---