app:
  name: linuxtips
  namespace: linuxtips
  createNamespace: true
  iam: ""

  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

  capacity:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
    autoscaling:
      min: 1
      max: 5
  rollout:
    revisionHistoryLimit: 3
    version: v1
    strategy:
      canary:
        enabled: true
        steps:
          - setWeight: 20
          - pause: {duration: 30s}
          - setWeight: 40
          - pause: {duration: 30s}
          - setWeight: 60
          - pause: {duration: 30s}
          - setWeight: 80
          - pause: {duration: 30s}
          - setWeight: 100
          - pause: {duration: 30s}