app:
  name: linuxtips
  namespace: linuxtips
  image:
    repository: fidelissauro/chip
    tag: v1
    pullPolicy: IfNotPresent
  createNamespace: true
  iam: ""

  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: https
      port: 443
      targetPort: 443

  capacity:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 200m
      memory: 256Mi
    autoscaling:
      min: 1
      max: 5
    nodepool:
      enabled: false
      name: general

  rollout:
    revisionHistoryLimit: 3
    version: v1
    strategy:
      canary:
        enabled: true
        steps:
          - setWeight: 20
          - pause: {duration: 30s}
          - setWeight: 40
          - pause: {duration: 30s}
          - setWeight: 60
          - pause: {duration: 30s}
          - setWeight: 80
          - pause: {duration: 30s}
          - setWeight: 100
          - pause: {duration: 30s}
  
  probes:
    startupProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
      httpGet:
        path: /
        port: 80
    readinessProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
      httpGet:
        path: /
        port: 80
    livenessProbe:
      enabled: true
      failureThreshold: 10
      periodSeconds: 10
      httpGet:
        path: /
        port: 80
  envs:
    - name: CHAOS_MONKEY_ENABLED
      value: "false"
    - name: CHAOS_MONKEY_MODE
      value: critical
    - name: CHAOS_MONKEY_LATENCY
      value: "true"
    - name: CHAOS_MONKEY_EXCEPTION
      value: "true"
    - name: CHAOS_MONKEY_APP_KILLER
      value: "true"
    - name: CHAOS_MONKEY_MEMORY
      value: "true"
    - name: VERSION
      value: v4

  istio:
    host: linuxtips.tiagots86.com.br
    gateway:
      enabled: true
      protocol: HTTP
      port: 80

    virtualService:
      enabled: true
      http:
        enabled: true
        port: 80
        retries:
          attempts: 1
          perTryTimeout: 2s
          retryOn: 5xx